// Code generated by go generate; DO NOT EDIT.
package require

import (
	assert "github.com/stretchr/testify/assert"
	upstream "github.com/stretchr/testify/require"
	"net/http"
	"net/url"
	"time"
)

func Condition(t TestingT, comp assert.Comparison, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Condition(t, comp, msgAndArgs...)
}
func Conditionf(t TestingT, comp assert.Comparison, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Conditionf(t, comp, msg, args...)
}
func Contains(t TestingT, s interface{}, contains interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Contains(t, s, contains, msgAndArgs...)
}
func Containsf(t TestingT, s interface{}, contains interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Containsf(t, s, contains, msg, args...)
}
func DirExists(t TestingT, path string, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.DirExists(t, path, msgAndArgs...)
}
func DirExistsf(t TestingT, path string, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.DirExistsf(t, path, msg, args...)
}
func ElementsMatch(t TestingT, listA interface{}, listB interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.ElementsMatch(t, listA, listB, msgAndArgs...)
}
func ElementsMatchf(t TestingT, listA interface{}, listB interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.ElementsMatchf(t, listA, listB, msg, args...)
}
func Empty(t TestingT, object interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Empty(t, object, msgAndArgs...)
}
func Emptyf(t TestingT, object interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Emptyf(t, object, msg, args...)
}
func EqualError(t TestingT, theError error, errString string, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.EqualError(t, theError, errString, msgAndArgs...)
}
func EqualErrorf(t TestingT, theError error, errString string, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.EqualErrorf(t, theError, errString, msg, args...)
}
func EqualExportedValues(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.EqualExportedValues(t, expected, actual, msgAndArgs...)
}
func EqualExportedValuesf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.EqualExportedValuesf(t, expected, actual, msg, args...)
}
func EqualValues(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.EqualValues(t, expected, actual, msgAndArgs...)
}
func EqualValuesf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.EqualValuesf(t, expected, actual, msg, args...)
}
func Error(t TestingT, err error, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Error(t, err, msgAndArgs...)
}
func ErrorAs(t TestingT, err error, target interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.ErrorAs(t, err, target, msgAndArgs...)
}
func ErrorAsf(t TestingT, err error, target interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.ErrorAsf(t, err, target, msg, args...)
}
func ErrorContains(t TestingT, theError error, contains string, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.ErrorContains(t, theError, contains, msgAndArgs...)
}
func ErrorContainsf(t TestingT, theError error, contains string, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.ErrorContainsf(t, theError, contains, msg, args...)
}
func ErrorIs(t TestingT, err error, target error, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.ErrorIs(t, err, target, msgAndArgs...)
}
func ErrorIsf(t TestingT, err error, target error, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.ErrorIsf(t, err, target, msg, args...)
}
func Errorf(t TestingT, err error, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Errorf(t, err, msg, args...)
}
func Eventually(t TestingT, condition func() bool, waitFor time.Duration, tick time.Duration, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Eventually(t, condition, waitFor, tick, msgAndArgs...)
}
func EventuallyWithT(t TestingT, condition func(collect *assert.CollectT), waitFor time.Duration, tick time.Duration, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.EventuallyWithT(t, condition, waitFor, tick, msgAndArgs...)
}
func EventuallyWithTf(t TestingT, condition func(collect *assert.CollectT), waitFor time.Duration, tick time.Duration, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.EventuallyWithTf(t, condition, waitFor, tick, msg, args...)
}
func Eventuallyf(t TestingT, condition func() bool, waitFor time.Duration, tick time.Duration, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Eventuallyf(t, condition, waitFor, tick, msg, args...)
}
func Exactly(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Exactly(t, expected, actual, msgAndArgs...)
}
func Exactlyf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Exactlyf(t, expected, actual, msg, args...)
}
func Fail(t TestingT, failureMessage string, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Fail(t, failureMessage, msgAndArgs...)
}
func FailNow(t TestingT, failureMessage string, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.FailNow(t, failureMessage, msgAndArgs...)
}
func FailNowf(t TestingT, failureMessage string, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.FailNowf(t, failureMessage, msg, args...)
}
func Failf(t TestingT, failureMessage string, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Failf(t, failureMessage, msg, args...)
}
func False(t TestingT, value bool, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.False(t, value, msgAndArgs...)
}
func Falsef(t TestingT, value bool, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Falsef(t, value, msg, args...)
}
func FileExists(t TestingT, path string, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.FileExists(t, path, msgAndArgs...)
}
func FileExistsf(t TestingT, path string, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.FileExistsf(t, path, msg, args...)
}
func Greater(t TestingT, e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Greater(t, e1, e2, msgAndArgs...)
}
func GreaterOrEqual(t TestingT, e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.GreaterOrEqual(t, e1, e2, msgAndArgs...)
}
func GreaterOrEqualf(t TestingT, e1 interface{}, e2 interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.GreaterOrEqualf(t, e1, e2, msg, args...)
}
func Greaterf(t TestingT, e1 interface{}, e2 interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Greaterf(t, e1, e2, msg, args...)
}
func HTTPBodyContains(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, str interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.HTTPBodyContains(t, handler, method, url, values, str, msgAndArgs...)
}
func HTTPBodyContainsf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, str interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.HTTPBodyContainsf(t, handler, method, url, values, str, msg, args...)
}
func HTTPBodyNotContains(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, str interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.HTTPBodyNotContains(t, handler, method, url, values, str, msgAndArgs...)
}
func HTTPBodyNotContainsf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, str interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.HTTPBodyNotContainsf(t, handler, method, url, values, str, msg, args...)
}
func HTTPError(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.HTTPError(t, handler, method, url, values, msgAndArgs...)
}
func HTTPErrorf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.HTTPErrorf(t, handler, method, url, values, msg, args...)
}
func HTTPRedirect(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.HTTPRedirect(t, handler, method, url, values, msgAndArgs...)
}
func HTTPRedirectf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.HTTPRedirectf(t, handler, method, url, values, msg, args...)
}
func HTTPStatusCode(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, statuscode int, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.HTTPStatusCode(t, handler, method, url, values, statuscode, msgAndArgs...)
}
func HTTPStatusCodef(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, statuscode int, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.HTTPStatusCodef(t, handler, method, url, values, statuscode, msg, args...)
}
func HTTPSuccess(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.HTTPSuccess(t, handler, method, url, values, msgAndArgs...)
}
func HTTPSuccessf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.HTTPSuccessf(t, handler, method, url, values, msg, args...)
}
func Implements(t TestingT, interfaceObject interface{}, object interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Implements(t, interfaceObject, object, msgAndArgs...)
}
func Implementsf(t TestingT, interfaceObject interface{}, object interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Implementsf(t, interfaceObject, object, msg, args...)
}
func InDelta(t TestingT, expected interface{}, actual interface{}, delta float64, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.InDelta(t, expected, actual, delta, msgAndArgs...)
}
func InDeltaMapValues(t TestingT, expected interface{}, actual interface{}, delta float64, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.InDeltaMapValues(t, expected, actual, delta, msgAndArgs...)
}
func InDeltaMapValuesf(t TestingT, expected interface{}, actual interface{}, delta float64, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.InDeltaMapValuesf(t, expected, actual, delta, msg, args...)
}
func InDeltaSlice(t TestingT, expected interface{}, actual interface{}, delta float64, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.InDeltaSlice(t, expected, actual, delta, msgAndArgs...)
}
func InDeltaSlicef(t TestingT, expected interface{}, actual interface{}, delta float64, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.InDeltaSlicef(t, expected, actual, delta, msg, args...)
}
func InDeltaf(t TestingT, expected interface{}, actual interface{}, delta float64, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.InDeltaf(t, expected, actual, delta, msg, args...)
}
func InEpsilon(t TestingT, expected interface{}, actual interface{}, epsilon float64, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.InEpsilon(t, expected, actual, epsilon, msgAndArgs...)
}
func InEpsilonSlice(t TestingT, expected interface{}, actual interface{}, epsilon float64, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.InEpsilonSlice(t, expected, actual, epsilon, msgAndArgs...)
}
func InEpsilonSlicef(t TestingT, expected interface{}, actual interface{}, epsilon float64, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.InEpsilonSlicef(t, expected, actual, epsilon, msg, args...)
}
func InEpsilonf(t TestingT, expected interface{}, actual interface{}, epsilon float64, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.InEpsilonf(t, expected, actual, epsilon, msg, args...)
}
func IsDecreasing(t TestingT, object interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.IsDecreasing(t, object, msgAndArgs...)
}
func IsDecreasingf(t TestingT, object interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.IsDecreasingf(t, object, msg, args...)
}
func IsIncreasing(t TestingT, object interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.IsIncreasing(t, object, msgAndArgs...)
}
func IsIncreasingf(t TestingT, object interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.IsIncreasingf(t, object, msg, args...)
}
func IsNonDecreasing(t TestingT, object interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.IsNonDecreasing(t, object, msgAndArgs...)
}
func IsNonDecreasingf(t TestingT, object interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.IsNonDecreasingf(t, object, msg, args...)
}
func IsNonIncreasing(t TestingT, object interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.IsNonIncreasing(t, object, msgAndArgs...)
}
func IsNonIncreasingf(t TestingT, object interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.IsNonIncreasingf(t, object, msg, args...)
}
func IsNotType(t TestingT, theType interface{}, object interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.IsNotType(t, theType, object, msgAndArgs...)
}
func IsNotTypef(t TestingT, theType interface{}, object interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.IsNotTypef(t, theType, object, msg, args...)
}
func IsType(t TestingT, expectedType interface{}, object interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.IsType(t, expectedType, object, msgAndArgs...)
}
func IsTypef(t TestingT, expectedType interface{}, object interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.IsTypef(t, expectedType, object, msg, args...)
}
func JSONEq(t TestingT, expected string, actual string, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.JSONEq(t, expected, actual, msgAndArgs...)
}
func JSONEqf(t TestingT, expected string, actual string, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.JSONEqf(t, expected, actual, msg, args...)
}
func Len(t TestingT, object interface{}, length int, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Len(t, object, length, msgAndArgs...)
}
func Lenf(t TestingT, object interface{}, length int, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Lenf(t, object, length, msg, args...)
}
func Less(t TestingT, e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Less(t, e1, e2, msgAndArgs...)
}
func LessOrEqual(t TestingT, e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.LessOrEqual(t, e1, e2, msgAndArgs...)
}
func LessOrEqualf(t TestingT, e1 interface{}, e2 interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.LessOrEqualf(t, e1, e2, msg, args...)
}
func Lessf(t TestingT, e1 interface{}, e2 interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Lessf(t, e1, e2, msg, args...)
}
func Negative(t TestingT, e interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Negative(t, e, msgAndArgs...)
}
func Negativef(t TestingT, e interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Negativef(t, e, msg, args...)
}
func Never(t TestingT, condition func() bool, waitFor time.Duration, tick time.Duration, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Never(t, condition, waitFor, tick, msgAndArgs...)
}
func Neverf(t TestingT, condition func() bool, waitFor time.Duration, tick time.Duration, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Neverf(t, condition, waitFor, tick, msg, args...)
}
func Nil(t TestingT, object interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Nil(t, object, msgAndArgs...)
}
func Nilf(t TestingT, object interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Nilf(t, object, msg, args...)
}
func NoDirExists(t TestingT, path string, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.NoDirExists(t, path, msgAndArgs...)
}
func NoDirExistsf(t TestingT, path string, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.NoDirExistsf(t, path, msg, args...)
}
func NoError(t TestingT, err error, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.NoError(t, err, msgAndArgs...)
}
func NoErrorf(t TestingT, err error, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.NoErrorf(t, err, msg, args...)
}
func NoFileExists(t TestingT, path string, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.NoFileExists(t, path, msgAndArgs...)
}
func NoFileExistsf(t TestingT, path string, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.NoFileExistsf(t, path, msg, args...)
}
func NotContains(t TestingT, s interface{}, contains interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.NotContains(t, s, contains, msgAndArgs...)
}
func NotContainsf(t TestingT, s interface{}, contains interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.NotContainsf(t, s, contains, msg, args...)
}
func NotElementsMatch(t TestingT, listA interface{}, listB interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.NotElementsMatch(t, listA, listB, msgAndArgs...)
}
func NotElementsMatchf(t TestingT, listA interface{}, listB interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.NotElementsMatchf(t, listA, listB, msg, args...)
}
func NotEmpty(t TestingT, object interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.NotEmpty(t, object, msgAndArgs...)
}
func NotEmptyf(t TestingT, object interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.NotEmptyf(t, object, msg, args...)
}
func NotEqualValues(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.NotEqualValues(t, expected, actual, msgAndArgs...)
}
func NotEqualValuesf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.NotEqualValuesf(t, expected, actual, msg, args...)
}
func NotErrorAs(t TestingT, err error, target interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.NotErrorAs(t, err, target, msgAndArgs...)
}
func NotErrorAsf(t TestingT, err error, target interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.NotErrorAsf(t, err, target, msg, args...)
}
func NotErrorIs(t TestingT, err error, target error, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.NotErrorIs(t, err, target, msgAndArgs...)
}
func NotErrorIsf(t TestingT, err error, target error, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.NotErrorIsf(t, err, target, msg, args...)
}
func NotImplements(t TestingT, interfaceObject interface{}, object interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.NotImplements(t, interfaceObject, object, msgAndArgs...)
}
func NotImplementsf(t TestingT, interfaceObject interface{}, object interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.NotImplementsf(t, interfaceObject, object, msg, args...)
}
func NotNil(t TestingT, object interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.NotNil(t, object, msgAndArgs...)
}
func NotNilf(t TestingT, object interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.NotNilf(t, object, msg, args...)
}
func NotPanics(t TestingT, f assert.PanicTestFunc, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.NotPanics(t, f, msgAndArgs...)
}
func NotPanicsf(t TestingT, f assert.PanicTestFunc, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.NotPanicsf(t, f, msg, args...)
}
func NotRegexp(t TestingT, rx interface{}, str interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.NotRegexp(t, rx, str, msgAndArgs...)
}
func NotRegexpf(t TestingT, rx interface{}, str interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.NotRegexpf(t, rx, str, msg, args...)
}
func NotSame(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.NotSame(t, expected, actual, msgAndArgs...)
}
func NotSamef(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.NotSamef(t, expected, actual, msg, args...)
}
func NotSubset(t TestingT, list interface{}, subset interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.NotSubset(t, list, subset, msgAndArgs...)
}
func NotSubsetf(t TestingT, list interface{}, subset interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.NotSubsetf(t, list, subset, msg, args...)
}
func NotZero(t TestingT, i interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.NotZero(t, i, msgAndArgs...)
}
func NotZerof(t TestingT, i interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.NotZerof(t, i, msg, args...)
}
func Panics(t TestingT, f assert.PanicTestFunc, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Panics(t, f, msgAndArgs...)
}
func PanicsWithError(t TestingT, errString string, f assert.PanicTestFunc, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.PanicsWithError(t, errString, f, msgAndArgs...)
}
func PanicsWithErrorf(t TestingT, errString string, f assert.PanicTestFunc, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.PanicsWithErrorf(t, errString, f, msg, args...)
}
func PanicsWithValue(t TestingT, expected interface{}, f assert.PanicTestFunc, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.PanicsWithValue(t, expected, f, msgAndArgs...)
}
func PanicsWithValuef(t TestingT, expected interface{}, f assert.PanicTestFunc, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.PanicsWithValuef(t, expected, f, msg, args...)
}
func Panicsf(t TestingT, f assert.PanicTestFunc, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Panicsf(t, f, msg, args...)
}
func Positive(t TestingT, e interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Positive(t, e, msgAndArgs...)
}
func Positivef(t TestingT, e interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Positivef(t, e, msg, args...)
}
func Regexp(t TestingT, rx interface{}, str interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Regexp(t, rx, str, msgAndArgs...)
}
func Regexpf(t TestingT, rx interface{}, str interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Regexpf(t, rx, str, msg, args...)
}
func Same(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Same(t, expected, actual, msgAndArgs...)
}
func Samef(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Samef(t, expected, actual, msg, args...)
}
func Subset(t TestingT, list interface{}, subset interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Subset(t, list, subset, msgAndArgs...)
}
func Subsetf(t TestingT, list interface{}, subset interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Subsetf(t, list, subset, msg, args...)
}
func True(t TestingT, value bool, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.True(t, value, msgAndArgs...)
}
func Truef(t TestingT, value bool, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Truef(t, value, msg, args...)
}
func WithinDuration(t TestingT, expected time.Time, actual time.Time, delta time.Duration, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.WithinDuration(t, expected, actual, delta, msgAndArgs...)
}
func WithinDurationf(t TestingT, expected time.Time, actual time.Time, delta time.Duration, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.WithinDurationf(t, expected, actual, delta, msg, args...)
}
func WithinRange(t TestingT, actual time.Time, start time.Time, end time.Time, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.WithinRange(t, actual, start, end, msgAndArgs...)
}
func WithinRangef(t TestingT, actual time.Time, start time.Time, end time.Time, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.WithinRangef(t, actual, start, end, msg, args...)
}
func YAMLEq(t TestingT, expected string, actual string, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.YAMLEq(t, expected, actual, msgAndArgs...)
}
func YAMLEqf(t TestingT, expected string, actual string, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.YAMLEqf(t, expected, actual, msg, args...)
}
func Zero(t TestingT, i interface{}, msgAndArgs ...interface{}) {
	markHelper(t).Helper()
	upstream.Zero(t, i, msgAndArgs...)
}
func Zerof(t TestingT, i interface{}, msg string, args ...interface{}) {
	markHelper(t).Helper()
	upstream.Zerof(t, i, msg, args...)
}

type BoolAssertionFunc = upstream.BoolAssertionFunc
type ComparisonAssertionFunc = upstream.ComparisonAssertionFunc
type ErrorAssertionFunc = upstream.ErrorAssertionFunc
type TestingT = upstream.TestingT
type ValueAssertionFunc = upstream.ValueAssertionFunc
