// Code generated by go generate; DO NOT EDIT.
package assert

import (
	upstream "github.com/stretchr/testify/assert"
	"net/http"
	"net/url"
	"time"
)

func CallerInfo() []string { return upstream.CallerInfo() }
func Condition(t TestingT, comp Comparison, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Condition(t, comp, msgAndArgs...)
}
func Conditionf(t TestingT, comp Comparison, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Conditionf(t, comp, msg, args...)
}
func Contains(t TestingT, s, contains interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Contains(t, s, contains, msgAndArgs...)
}
func Containsf(t TestingT, s interface{}, contains interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Containsf(t, s, contains, msg, args...)
}
func DirExists(t TestingT, path string, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.DirExists(t, path, msgAndArgs...)
}
func DirExistsf(t TestingT, path string, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.DirExistsf(t, path, msg, args...)
}
func ElementsMatch(t TestingT, listA, listB interface{}, msgAndArgs ...interface{}) (ok bool) {
	markHelper(t).Helper()
	return upstream.ElementsMatch(t, listA, listB, msgAndArgs...)
}
func ElementsMatchf(t TestingT, listA interface{}, listB interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.ElementsMatchf(t, listA, listB, msg, args...)
}
func Empty(t TestingT, object interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Empty(t, object, msgAndArgs...)
}
func Emptyf(t TestingT, object interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Emptyf(t, object, msg, args...)
}
func EqualError(t TestingT, theError error, errString string, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.EqualError(t, theError, errString, msgAndArgs...)
}
func EqualErrorf(t TestingT, theError error, errString string, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.EqualErrorf(t, theError, errString, msg, args...)
}
func EqualExportedValues(t TestingT, expected, actual interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.EqualExportedValues(t, expected, actual, msgAndArgs...)
}
func EqualExportedValuesf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.EqualExportedValuesf(t, expected, actual, msg, args...)
}
func EqualValues(t TestingT, expected, actual interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.EqualValues(t, expected, actual, msgAndArgs...)
}
func EqualValuesf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.EqualValuesf(t, expected, actual, msg, args...)
}
func Error(t TestingT, err error, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Error(t, err, msgAndArgs...)
}
func ErrorAs(t TestingT, err error, target interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.ErrorAs(t, err, target, msgAndArgs...)
}
func ErrorAsf(t TestingT, err error, target interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.ErrorAsf(t, err, target, msg, args...)
}
func ErrorContains(t TestingT, theError error, contains string, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.ErrorContains(t, theError, contains, msgAndArgs...)
}
func ErrorContainsf(t TestingT, theError error, contains string, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.ErrorContainsf(t, theError, contains, msg, args...)
}
func ErrorIs(t TestingT, err, target error, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.ErrorIs(t, err, target, msgAndArgs...)
}
func ErrorIsf(t TestingT, err error, target error, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.ErrorIsf(t, err, target, msg, args...)
}
func Errorf(t TestingT, err error, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Errorf(t, err, msg, args...)
}
func Eventually(t TestingT, condition func() bool, waitFor time.Duration, tick time.Duration, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Eventually(t, condition, waitFor, tick, msgAndArgs...)
}
func EventuallyWithT(t TestingT, condition func(collect *CollectT), waitFor time.Duration, tick time.Duration, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.EventuallyWithT(t, condition, waitFor, tick, msgAndArgs...)
}
func EventuallyWithTf(t TestingT, condition func(collect *CollectT), waitFor time.Duration, tick time.Duration, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.EventuallyWithTf(t, condition, waitFor, tick, msg, args...)
}
func Eventuallyf(t TestingT, condition func() bool, waitFor time.Duration, tick time.Duration, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Eventuallyf(t, condition, waitFor, tick, msg, args...)
}
func Exactly(t TestingT, expected, actual interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Exactly(t, expected, actual, msgAndArgs...)
}
func Exactlyf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Exactlyf(t, expected, actual, msg, args...)
}
func Fail(t TestingT, failureMessage string, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Fail(t, failureMessage, msgAndArgs...)
}
func FailNow(t TestingT, failureMessage string, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.FailNow(t, failureMessage, msgAndArgs...)
}
func FailNowf(t TestingT, failureMessage string, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.FailNowf(t, failureMessage, msg, args...)
}
func Failf(t TestingT, failureMessage string, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Failf(t, failureMessage, msg, args...)
}
func False(t TestingT, value bool, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.False(t, value, msgAndArgs...)
}
func Falsef(t TestingT, value bool, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Falsef(t, value, msg, args...)
}
func FileExists(t TestingT, path string, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.FileExists(t, path, msgAndArgs...)
}
func FileExistsf(t TestingT, path string, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.FileExistsf(t, path, msg, args...)
}
func Greater(t TestingT, e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Greater(t, e1, e2, msgAndArgs...)
}
func GreaterOrEqual(t TestingT, e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.GreaterOrEqual(t, e1, e2, msgAndArgs...)
}
func GreaterOrEqualf(t TestingT, e1 interface{}, e2 interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.GreaterOrEqualf(t, e1, e2, msg, args...)
}
func Greaterf(t TestingT, e1 interface{}, e2 interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Greaterf(t, e1, e2, msg, args...)
}
func HTTPBody(handler http.HandlerFunc, method, url string, values url.Values) string {
	return upstream.HTTPBody(handler, method, url, values)
}
func HTTPBodyContains(t TestingT, handler http.HandlerFunc, method, url string, values url.Values, str interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.HTTPBodyContains(t, handler, method, url, values, str, msgAndArgs...)
}
func HTTPBodyContainsf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, str interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.HTTPBodyContainsf(t, handler, method, url, values, str, msg, args...)
}
func HTTPBodyNotContains(t TestingT, handler http.HandlerFunc, method, url string, values url.Values, str interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.HTTPBodyNotContains(t, handler, method, url, values, str, msgAndArgs...)
}
func HTTPBodyNotContainsf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, str interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.HTTPBodyNotContainsf(t, handler, method, url, values, str, msg, args...)
}
func HTTPError(t TestingT, handler http.HandlerFunc, method, url string, values url.Values, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.HTTPError(t, handler, method, url, values, msgAndArgs...)
}
func HTTPErrorf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.HTTPErrorf(t, handler, method, url, values, msg, args...)
}
func HTTPRedirect(t TestingT, handler http.HandlerFunc, method, url string, values url.Values, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.HTTPRedirect(t, handler, method, url, values, msgAndArgs...)
}
func HTTPRedirectf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.HTTPRedirectf(t, handler, method, url, values, msg, args...)
}
func HTTPStatusCode(t TestingT, handler http.HandlerFunc, method, url string, values url.Values, statuscode int, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.HTTPStatusCode(t, handler, method, url, values, statuscode, msgAndArgs...)
}
func HTTPStatusCodef(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, statuscode int, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.HTTPStatusCodef(t, handler, method, url, values, statuscode, msg, args...)
}
func HTTPSuccess(t TestingT, handler http.HandlerFunc, method, url string, values url.Values, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.HTTPSuccess(t, handler, method, url, values, msgAndArgs...)
}
func HTTPSuccessf(t TestingT, handler http.HandlerFunc, method string, url string, values url.Values, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.HTTPSuccessf(t, handler, method, url, values, msg, args...)
}
func Implements(t TestingT, interfaceObject interface{}, object interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Implements(t, interfaceObject, object, msgAndArgs...)
}
func Implementsf(t TestingT, interfaceObject interface{}, object interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Implementsf(t, interfaceObject, object, msg, args...)
}
func InDelta(t TestingT, expected, actual interface{}, delta float64, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.InDelta(t, expected, actual, delta, msgAndArgs...)
}
func InDeltaMapValues(t TestingT, expected, actual interface{}, delta float64, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.InDeltaMapValues(t, expected, actual, delta, msgAndArgs...)
}
func InDeltaMapValuesf(t TestingT, expected interface{}, actual interface{}, delta float64, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.InDeltaMapValuesf(t, expected, actual, delta, msg, args...)
}
func InDeltaSlice(t TestingT, expected, actual interface{}, delta float64, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.InDeltaSlice(t, expected, actual, delta, msgAndArgs...)
}
func InDeltaSlicef(t TestingT, expected interface{}, actual interface{}, delta float64, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.InDeltaSlicef(t, expected, actual, delta, msg, args...)
}
func InDeltaf(t TestingT, expected interface{}, actual interface{}, delta float64, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.InDeltaf(t, expected, actual, delta, msg, args...)
}
func InEpsilon(t TestingT, expected, actual interface{}, epsilon float64, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.InEpsilon(t, expected, actual, epsilon, msgAndArgs...)
}
func InEpsilonSlice(t TestingT, expected, actual interface{}, epsilon float64, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.InEpsilonSlice(t, expected, actual, epsilon, msgAndArgs...)
}
func InEpsilonSlicef(t TestingT, expected interface{}, actual interface{}, epsilon float64, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.InEpsilonSlicef(t, expected, actual, epsilon, msg, args...)
}
func InEpsilonf(t TestingT, expected interface{}, actual interface{}, epsilon float64, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.InEpsilonf(t, expected, actual, epsilon, msg, args...)
}
func IsDecreasing(t TestingT, object interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.IsDecreasing(t, object, msgAndArgs...)
}
func IsDecreasingf(t TestingT, object interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.IsDecreasingf(t, object, msg, args...)
}
func IsIncreasing(t TestingT, object interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.IsIncreasing(t, object, msgAndArgs...)
}
func IsIncreasingf(t TestingT, object interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.IsIncreasingf(t, object, msg, args...)
}
func IsNonDecreasing(t TestingT, object interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.IsNonDecreasing(t, object, msgAndArgs...)
}
func IsNonDecreasingf(t TestingT, object interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.IsNonDecreasingf(t, object, msg, args...)
}
func IsNonIncreasing(t TestingT, object interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.IsNonIncreasing(t, object, msgAndArgs...)
}
func IsNonIncreasingf(t TestingT, object interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.IsNonIncreasingf(t, object, msg, args...)
}
func IsNotType(t TestingT, theType, object interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.IsNotType(t, theType, object, msgAndArgs...)
}
func IsNotTypef(t TestingT, theType interface{}, object interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.IsNotTypef(t, theType, object, msg, args...)
}
func IsType(t TestingT, expectedType, object interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.IsType(t, expectedType, object, msgAndArgs...)
}
func IsTypef(t TestingT, expectedType interface{}, object interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.IsTypef(t, expectedType, object, msg, args...)
}
func JSONEq(t TestingT, expected string, actual string, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.JSONEq(t, expected, actual, msgAndArgs...)
}
func JSONEqf(t TestingT, expected string, actual string, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.JSONEqf(t, expected, actual, msg, args...)
}
func Len(t TestingT, object interface{}, length int, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Len(t, object, length, msgAndArgs...)
}
func Lenf(t TestingT, object interface{}, length int, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Lenf(t, object, length, msg, args...)
}
func Less(t TestingT, e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Less(t, e1, e2, msgAndArgs...)
}
func LessOrEqual(t TestingT, e1 interface{}, e2 interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.LessOrEqual(t, e1, e2, msgAndArgs...)
}
func LessOrEqualf(t TestingT, e1 interface{}, e2 interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.LessOrEqualf(t, e1, e2, msg, args...)
}
func Lessf(t TestingT, e1 interface{}, e2 interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Lessf(t, e1, e2, msg, args...)
}
func Negative(t TestingT, e interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Negative(t, e, msgAndArgs...)
}
func Negativef(t TestingT, e interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Negativef(t, e, msg, args...)
}
func Never(t TestingT, condition func() bool, waitFor time.Duration, tick time.Duration, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Never(t, condition, waitFor, tick, msgAndArgs...)
}
func Neverf(t TestingT, condition func() bool, waitFor time.Duration, tick time.Duration, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Neverf(t, condition, waitFor, tick, msg, args...)
}
func Nil(t TestingT, object interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Nil(t, object, msgAndArgs...)
}
func Nilf(t TestingT, object interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Nilf(t, object, msg, args...)
}
func NoDirExists(t TestingT, path string, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NoDirExists(t, path, msgAndArgs...)
}
func NoDirExistsf(t TestingT, path string, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NoDirExistsf(t, path, msg, args...)
}
func NoError(t TestingT, err error, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NoError(t, err, msgAndArgs...)
}
func NoErrorf(t TestingT, err error, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NoErrorf(t, err, msg, args...)
}
func NoFileExists(t TestingT, path string, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NoFileExists(t, path, msgAndArgs...)
}
func NoFileExistsf(t TestingT, path string, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NoFileExistsf(t, path, msg, args...)
}
func NotContains(t TestingT, s, contains interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotContains(t, s, contains, msgAndArgs...)
}
func NotContainsf(t TestingT, s interface{}, contains interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotContainsf(t, s, contains, msg, args...)
}
func NotElementsMatch(t TestingT, listA, listB interface{}, msgAndArgs ...interface{}) (ok bool) {
	markHelper(t).Helper()
	return upstream.NotElementsMatch(t, listA, listB, msgAndArgs...)
}
func NotElementsMatchf(t TestingT, listA interface{}, listB interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotElementsMatchf(t, listA, listB, msg, args...)
}
func NotEmpty(t TestingT, object interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotEmpty(t, object, msgAndArgs...)
}
func NotEmptyf(t TestingT, object interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotEmptyf(t, object, msg, args...)
}
func NotEqualValues(t TestingT, expected, actual interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotEqualValues(t, expected, actual, msgAndArgs...)
}
func NotEqualValuesf(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotEqualValuesf(t, expected, actual, msg, args...)
}
func NotErrorAs(t TestingT, err error, target interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotErrorAs(t, err, target, msgAndArgs...)
}
func NotErrorAsf(t TestingT, err error, target interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotErrorAsf(t, err, target, msg, args...)
}
func NotErrorIs(t TestingT, err, target error, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotErrorIs(t, err, target, msgAndArgs...)
}
func NotErrorIsf(t TestingT, err error, target error, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotErrorIsf(t, err, target, msg, args...)
}
func NotImplements(t TestingT, interfaceObject interface{}, object interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotImplements(t, interfaceObject, object, msgAndArgs...)
}
func NotImplementsf(t TestingT, interfaceObject interface{}, object interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotImplementsf(t, interfaceObject, object, msg, args...)
}
func NotNil(t TestingT, object interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotNil(t, object, msgAndArgs...)
}
func NotNilf(t TestingT, object interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotNilf(t, object, msg, args...)
}
func NotPanics(t TestingT, f PanicTestFunc, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotPanics(t, f, msgAndArgs...)
}
func NotPanicsf(t TestingT, f PanicTestFunc, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotPanicsf(t, f, msg, args...)
}
func NotRegexp(t TestingT, rx interface{}, str interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotRegexp(t, rx, str, msgAndArgs...)
}
func NotRegexpf(t TestingT, rx interface{}, str interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotRegexpf(t, rx, str, msg, args...)
}
func NotSame(t TestingT, expected, actual interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotSame(t, expected, actual, msgAndArgs...)
}
func NotSamef(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotSamef(t, expected, actual, msg, args...)
}
func NotSubset(t TestingT, list, subset interface{}, msgAndArgs ...interface{}) (ok bool) {
	markHelper(t).Helper()
	return upstream.NotSubset(t, list, subset, msgAndArgs...)
}
func NotSubsetf(t TestingT, list interface{}, subset interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotSubsetf(t, list, subset, msg, args...)
}
func NotZero(t TestingT, i interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotZero(t, i, msgAndArgs...)
}
func NotZerof(t TestingT, i interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.NotZerof(t, i, msg, args...)
}
func ObjectsAreEqualValues(expected, actual interface{}) bool {
	return upstream.ObjectsAreEqualValues(expected, actual)
}
func ObjectsExportedFieldsAreEqual(expected, actual interface{}) bool {
	return upstream.ObjectsExportedFieldsAreEqual(expected, actual)
}
func Panics(t TestingT, f PanicTestFunc, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Panics(t, f, msgAndArgs...)
}
func PanicsWithError(t TestingT, errString string, f PanicTestFunc, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.PanicsWithError(t, errString, f, msgAndArgs...)
}
func PanicsWithErrorf(t TestingT, errString string, f PanicTestFunc, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.PanicsWithErrorf(t, errString, f, msg, args...)
}
func PanicsWithValue(t TestingT, expected interface{}, f PanicTestFunc, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.PanicsWithValue(t, expected, f, msgAndArgs...)
}
func PanicsWithValuef(t TestingT, expected interface{}, f PanicTestFunc, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.PanicsWithValuef(t, expected, f, msg, args...)
}
func Panicsf(t TestingT, f PanicTestFunc, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Panicsf(t, f, msg, args...)
}
func Positive(t TestingT, e interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Positive(t, e, msgAndArgs...)
}
func Positivef(t TestingT, e interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Positivef(t, e, msg, args...)
}
func Regexp(t TestingT, rx interface{}, str interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Regexp(t, rx, str, msgAndArgs...)
}
func Regexpf(t TestingT, rx interface{}, str interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Regexpf(t, rx, str, msg, args...)
}
func Same(t TestingT, expected, actual interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Same(t, expected, actual, msgAndArgs...)
}
func Samef(t TestingT, expected interface{}, actual interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Samef(t, expected, actual, msg, args...)
}
func Subset(t TestingT, list, subset interface{}, msgAndArgs ...interface{}) (ok bool) {
	markHelper(t).Helper()
	return upstream.Subset(t, list, subset, msgAndArgs...)
}
func Subsetf(t TestingT, list interface{}, subset interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Subsetf(t, list, subset, msg, args...)
}
func True(t TestingT, value bool, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.True(t, value, msgAndArgs...)
}
func Truef(t TestingT, value bool, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Truef(t, value, msg, args...)
}
func WithinDuration(t TestingT, expected, actual time.Time, delta time.Duration, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.WithinDuration(t, expected, actual, delta, msgAndArgs...)
}
func WithinDurationf(t TestingT, expected time.Time, actual time.Time, delta time.Duration, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.WithinDurationf(t, expected, actual, delta, msg, args...)
}
func WithinRange(t TestingT, actual, start, end time.Time, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.WithinRange(t, actual, start, end, msgAndArgs...)
}
func WithinRangef(t TestingT, actual time.Time, start time.Time, end time.Time, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.WithinRangef(t, actual, start, end, msg, args...)
}
func YAMLEq(t TestingT, expected string, actual string, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.YAMLEq(t, expected, actual, msgAndArgs...)
}
func YAMLEqf(t TestingT, expected string, actual string, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.YAMLEqf(t, expected, actual, msg, args...)
}
func Zero(t TestingT, i interface{}, msgAndArgs ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Zero(t, i, msgAndArgs...)
}
func Zerof(t TestingT, i interface{}, msg string, args ...interface{}) bool {
	markHelper(t).Helper()
	return upstream.Zerof(t, i, msg, args...)
}

type BoolAssertionFunc = upstream.BoolAssertionFunc
type CollectT = upstream.CollectT
type CompareType = upstream.CompareType
type Comparison = upstream.Comparison
type ComparisonAssertionFunc = upstream.ComparisonAssertionFunc
type ErrorAssertionFunc = upstream.ErrorAssertionFunc
type PanicAssertionFunc = upstream.PanicAssertionFunc
type PanicTestFunc = upstream.PanicTestFunc
type TestingT = upstream.TestingT
type ValueAssertionFunc = upstream.ValueAssertionFunc

var AnError = upstream.AnError
